server {
    listen 80;
    listen [::]:80;
    server_name localhost;

   # =====================================================
    # Proxy to Frontend (React)
    # =====================================================
    location / {
        proxy_pass http://frontend:5173;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # =====================================================
    # Proxy to Node.js Backend API
    # =====================================================
    location /api/ {
        # Bắt buộc phải là http://api:5000 để gọi đúng tên container
        proxy_pass http://api:5000;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # =====================================================
    # Static Files (Uploads)
    # =====================================================
    location /uploads/ {
        alias /var/www/antiquestore/uploads/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}